using System;
using System.Collections.Generic;

#nullable disable

namespace AccessWebsite.Models.Advantage
{
    public partial class Product
    {
        public Product()
        {
            ProductDescriptions = new HashSet<ProductDescription>();
        }

        public string ComputerizedPartNumber { get; set; }
        public string ProductCode { get; set; }
        public string ProductName { get; set; }
        public string FirstComponentComputerizedPartNumber { get; set; }
        public string FirstPartComputerizedPartNumber { get; set; }
        public string BillOfMaterialLowestLevelNumber { get; set; }
        public string UnitOfMeasureCode { get; set; }
        public string ManufacturingRevisionLevelNumber { get; set; }
        public decimal? DrawingSize { get; set; }
        public string DrawingNumber { get; set; }
        public string FormerProductCode { get; set; }
        public string DrawingTypeCode { get; set; }
        public string ProductClassCode { get; set; }
        public string SortNumber { get; set; }
        public string ProductAbbreviation { get; set; }
        public string GeneralLedgerGroupCode { get; set; }
        public string ExcessReasonCode { get; set; }
        public decimal? StandardLaborCostAmount { get; set; }
        public DateTime? CreationDate { get; set; }
        public DateTime? LastActivityDate { get; set; }
        public DateTime? LastCycleCountDate { get; set; }
        public decimal? LastCycleCountQuantity { get; set; }
        public decimal? OnHandQuantity { get; set; }
        public decimal? ReceivingInInspectionQuantity { get; set; }
        public decimal? MonthToDateUsageQuantity { get; set; }
        public decimal? LastYearUsageQuantity { get; set; }
        public decimal? MinimumStockQuantity { get; set; }
        public decimal? MaximumStockQuantity { get; set; }
        public decimal? ReorderQuantity { get; set; }
        public decimal? EconomicOrderQuantity { get; set; }
        public decimal? MinimumOrderQuantity { get; set; }
        public decimal? MultipleOrderQuantity { get; set; }
        public decimal? MaximumOrderQuantity { get; set; }
        public decimal? OrderPeriodDay { get; set; }
        public decimal? SafetyStockQuantity { get; set; }
        public decimal? ManufacturingAllocationQuantity { get; set; }
        public decimal? MaterialReviewBoardQuantity { get; set; }
        public decimal? QuarantineQuantity { get; set; }
        public decimal? PurchasingLeadTimeDay { get; set; }
        public decimal? ManufacturingLeadTimeDay { get; set; }
        public decimal? ShrinkFactorPercent { get; set; }
        public DateTime? CuttOffDate { get; set; }
        public string InventoryCode { get; set; }
        public string ItemTypeCode { get; set; }
        public decimal? AverageCostAmount { get; set; }
        public decimal? BackOrderQuantity { get; set; }
        public DateTime? NextReceiptDate { get; set; }
        public decimal? NextReceiptQuantity { get; set; }
        public string PriceClassCode { get; set; }
        public string FirstRoutingRecordSequenceNumber { get; set; }
        public string LastRoutingRecordSequenceNumber { get; set; }
        public decimal? ShippingAllocationQuantity { get; set; }
        public string AccountingStatusCode { get; set; }
        public DateTime? LastNoShipDate { get; set; }
        public string AssemblyAllocationCode { get; set; }
        public string UnitStructureFlag { get; set; }
        public string ItemClassCode { get; set; }
        public string PlannerCode { get; set; }
        public string BuyerCode { get; set; }
        public string CostErrorFlag { get; set; }
        public decimal? DesiredInventoryStockDay { get; set; }
        public string InspectionRequiredFlag { get; set; }
        public decimal? DockToStockLeadTimeDay { get; set; }
        public DateTime? ManufacturingRevisionEffectiveDate { get; set; }
        public string ManufacturingRevisionEngineeringChangeOrderNumber { get; set; }
        public string EngineeringRevisionLevelNumber { get; set; }
        public DateTime? EngineeringRevisionEffectiveDate { get; set; }
        public string EngineeringRevisionEnginerringChangeOrderNumber { get; set; }
        public string SupersedesProductCode { get; set; }
        public decimal? Weight { get; set; }
        public decimal? CubeSpace { get; set; }
        public string PurchasingUnitOfMeasureCode { get; set; }
        public decimal? PurchasingUnitOfMeasureConversionRate { get; set; }
        public decimal? ShelfLifeDay { get; set; }
        public decimal? PackageQuantity { get; set; }
        public string ConfigurationCode { get; set; }
        public decimal? RunTimeHour { get; set; }
        public decimal? SetupTimeHour { get; set; }
        public decimal? MoveQueueTimeHour { get; set; }
        public string FirstSequenceNumber { get; set; }
        public string LastSequenceNumber { get; set; }
        public string EstimateCostCode { get; set; }
        public string ExtraCommissionGroupCode { get; set; }
        public string Dimension2Code { get; set; }
        public string Dimension3Code { get; set; }
        public decimal? ContractFirmWeek { get; set; }
        public string ConversionTypeCode { get; set; }
        public string Dimension4Code { get; set; }
        public string GroupTechnologyCode { get; set; }
        public string SubstituteProductCode { get; set; }
        public string PrimaryManufacturingWarehouseCode { get; set; }
        public string CommodityCode { get; set; }
        public string DefaultRoutingGroupCode { get; set; }
        public decimal? LevelSetupHour { get; set; }
        public decimal? LevelSetupAmount { get; set; }
        public decimal? LevelMachineHour { get; set; }
        public decimal? LevelMachineAmount { get; set; }
        public string UniversalProductCode { get; set; }
        public decimal? AddedWeight { get; set; }
        public string QualityControlCategoryCode { get; set; }
        public string ServiceComputerizedPartNumber { get; set; }
        public string OriginalComputerizedPartNumber { get; set; }
        public string SiteTrackFlag { get; set; }
        public string ConsumableRepairCode { get; set; }
        public string TemporaryComputerizedPartNumber { get; set; }
        public string OriginCountryCode { get; set; }
        public string TariffCode { get; set; }
        public string DangerousGoodCode { get; set; }
        public string ProductRequestReferenceNumber { get; set; }
        public string EngineeringRevisionNumber { get; set; }
        public string WarehousePlantFlag { get; set; }
        public string RoyaltyFlag { get; set; }
        public string MatrixCategoryCode { get; set; }
        public decimal? WeightFactorRate { get; set; }
        public decimal? SpecificGravity { get; set; }
        public string AffiliatedPurchaseFlag { get; set; }
        public decimal? ScrapPercent { get; set; }
        public string AlternateUniversalProductCode { get; set; }
        public string NonStockInventoryQuoteNumberLineNumber { get; set; }
        public decimal? RollUpWeight { get; set; }
        public decimal? CalculatedWeight { get; set; }
        public string QualityReferencenNumber { get; set; }
        public string ProductLineCode { get; set; }
        public string ExcludeWeightInAssemblyFlag { get; set; }
        public decimal? OneLevelWeight { get; set; }
        public decimal? CalculatedAddedWeight { get; set; }
        public decimal? WeightDifferencePercent { get; set; }
        public decimal? AddedWeightDifferencePercent { get; set; }
        public string WeightUpdateFlag { get; set; }
        public string PackagingLockedSwitchFlag { get; set; }
        public string NonReturnableCancellableFlag { get; set; }
        public DateTime? ExpirationDate { get; set; }
        public string ReferenceNumber { get; set; }
        public string DiameterAttributeCode { get; set; }
        public string LengthAttributeCode { get; set; }
        public string MaterialAttributeCode { get; set; }
        public string ClassAttributeCode { get; set; }
        public string ProductTypeAttributeCode { get; set; }
        public string CertificationAttributeCode { get; set; }
        public string ConnectionTypeAttributeCode { get; set; }
        public string ColorAttributeCode { get; set; }
        public string BrandIpexattributeCode { get; set; }
        public string FeatureAattributeCode { get; set; }
        public string StandardUnitOfMeasureTypeCode { get; set; }
        public string AttributeStatusCode { get; set; }
        public string Diameter1AttributeCode { get; set; }
        public string AngleAttributeCode { get; set; }
        public string ApplicationAttributeCode { get; set; }
        public string BrandIpexusattributeCode { get; set; }
        public string BrandMultiAttributeCode { get; set; }
        public string ComponentOptionAttributeCode { get; set; }
        public string Diameter2AttributeCode { get; set; }
        public string DimensionalStandardAttributeCode { get; set; }
        public string FeatureBattributeCode { get; set; }
        public string FunctionAttributeCode { get; set; }
        public string GlobeColorAttributeCode { get; set; }
        public string GlobeMaterialAttributeCode { get; set; }
        public string LengthToAttributeCode { get; set; }
        public string MountTypeAttributeCode { get; set; }
        public string OptionsAttributeCode { get; set; }
        public string PartNumberAttributeCode { get; set; }
        public string RadiusAttributeCode { get; set; }
        public string SealMaterialAttributeCode { get; set; }
        public string SeriesAttributeCode { get; set; }
        public string SizeAttributeCode { get; set; }
        public string ThicknessAttributeCode { get; set; }
        public string TorqueAttributeCode { get; set; }
        public string UseAttributeCode { get; set; }
        public string VoltageSignalAttributeCode { get; set; }
        public string WattAttributeCode { get; set; }
        public string Diameter3AttributeCode { get; set; }
        public string Diameter4AttributeCode { get; set; }
        public string FeaturesAttributeCode { get; set; }
        public string Attribute39Code { get; set; }
        public string Attribute40Code { get; set; }
        public string Attribute41Code { get; set; }
        public string Attribute42Code { get; set; }
        public string Attribute43Code { get; set; }
        public string Attribute44Code { get; set; }
        public string Attribute45Code { get; set; }
        public string AttributeGroupingCode { get; set; }
        public string AttributeCatalogNumber { get; set; }
        public string AttributeOriginalEquipmentManufacturerProductNumber { get; set; }
        public string AttributeDuplicateReasonCode { get; set; }
        public decimal? OuterDiameter { get; set; }
        public decimal? BellLength { get; set; }
        public string ProductCodeProductName { get; set; }
        public bool? ActiveFlag { get; set; }
        public string ProductNameProductCode { get; set; }

        public virtual ICollection<ProductDescription> ProductDescriptions { get; set; }
    }
}
